### PR TITLE
Fix documentation formatting and incorporate doc checks in travis-ci

### PR DESCRIPTION
**Pull request by dthvt**
Several modules had invalidly formatted doc strings.  Fixed formatting to the point where it will successfully display w/ ansible-doc.  Added a travis-ci hook to check future commits for valid doc string formatting.

### CODE REVIEW

**Comment by shinmog** [comment]
Just now saw this.  Same with this:  if I missed correcting the module docstring in the v210 branch, can you PR that?

**Comment by dthvt** [comment]
Now that I'm decompressed from work, I realized you meant PR against the v210 branch instead of develop.  I'll look at rebasing the edits against v210 and submit a new PR tomorrow.  Sorry for the slow thinking. haha

**Comment by dthvt** [comment]
Just realized I didn't thoroughly test the test (doh) and ansible-doc apparently doesn't return non-zero when it fails to load the doc.  I'll have to redo the integration.

More importantly, under v210 it seems like ansible-doc can't find the documentation templates being used.  And to be honest, I can't find them either.  I'm not familiar w/ doc template for 3rd party modules.  Where are they stored in the repo?  

I'm going to close this PR for the time being, as it's definitely not ready against v210.

**Comment by shinmog** [comment]
@dthvt 

The documentation fragments have to be referenced from Ansible core.  They are located [here](https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/doc_fragments/panos.py) in the code, but this turns into `./ansible/utils/module_docs_fragments/panos.py` when Ansible is installed.  Eventually Ansible will let documentation fragments be contained in the role itself (I assume), but this means that v2.1.0 can't release until Ansible 2.8 comes out.

So if you're wanting to play with this locally, just grab the above file and save it to your `./ansible/utils/module_docs_fragments/panos.py`.

**Comment by dthvt** [comment]
Got it.  I wasn't clear on how 3rd party doc fragments worked (or didn't work) & had assumed the doc fragment in the ansible repo was deprecated when the modules were.

I'll make another run at this when I can.

**Pull request closed without merging**
