### PR TITLE
Add panos_virtual_router and panos_bgp* modules

### PR DESCRIPTION
**Pull request by freakinhippie**
* panos_virtual_router
* panos_bgp
* panos_bgp_peer
* panos_bgp_peer_group

All of the panos_bgp* modules are dependent on the [pandevice PR #132](https://github.com/PaloAltoNetworks/pandevice/pull/132).

I'm working on more modules for the rest of the BGP configuration options, but they're still in progress.

### CODE REVIEW

**Comment by freakinhippie** [comment]
I've  run into a bit of a chicken and egg problem regarding the ansible module implementation for the Conditional Advertisements tab of BGP. Each rule requires at least one child Non-Exist filter and one Advertisement filter. Since these are child objects of the conditional advertisement rule, I'm unable to apply the rule without the child included, but I cannot create the child until the parent exists.

**Comment by freakinhippie** [comment]
I'm not sure why it is failing the Travis CI checks, all the errors were corrected.

**Comment by shinmog** [comment]
@freakinhippie 

The `pandevice` stuff has been merged, there will be a new release of it in the near future (just waiting to make sure there aren't other things that need to be added for Ansible's sake).  There are now conflicts between develop and this PR, so please resolve these when you can.

**Comment by freakinhippie** [comment]
@shinmog It is cleaned up now. Thanks.

**Pull request merged**
