### PR TITLE
Add PanOS Loopback module

### PR DESCRIPTION
**Pull request by geraint-jones-nz**
Hi Guys

Just a quick hack, I needed to setup loopbacks with ansible and there was seemingly no way to do it. So I added a new module.

### CODE REVIEW

**Comment by geraint-jones-nz** [comment]
I have found a few issues with this that I am going to fix.

However, can anyone answer why the default is to require an operation rather than default to trying add and failing back to update?

**Comment by geraint-jones-nz** [comment]
I am having a few issues with the VR interfaces API.

https://github.com/PaloAltoNetworks/pandevice/issues/113

Once resolved I will update.

**Comment by geraint-jones-nz** [comment]
Okay so I have cleaned up the code a little.

For some reason though it is still failing to set the zone on the loopback. Fails with the error `FAILED! => {"changed": false, "msg": "Virtual router Internet_eBGP does not exist"}` when in fact it very clearly exists...

Any idea @jtschichold / @ivanbojer ?

**Comment by shinmog** [comment]
@geraint-jones-nz 
We are in the process of transitioning over from using `operation` to using `state`, which is more in line with the Ansible standard.

Could you please update this PR at your earliest convenience?

**Comment by ivanbojer** [comment]
Closing the pull as it is stale.

**Comment by geraint-jones-nz** [comment]
I will update this, as it is still needed.

Can this be re-opened?

**Pull request closed without merging**
