### PR TITLE
panos_bgp_redistribute.py - fix example

### LINKED ISSUE #283: panos_bgp_redistribute - examples wrong
Examples show a BGP policy rule and says it's a peer group creation.

Will try to submit a pull request later for this, just don't want to forget.

### PR DESCRIPTION
**Pull request by dthvt**
Fixes #283

### CODE REVIEW

**Comment by shinmog** [comment]
@dthvt 

Hrm..  So, panos_bgp_redistribute hasn't been updated yet.  You want to update the module as a whole, and update the documentation while you're at it?

Alternatively I could update the module (will get to it eventually) and leave the docs alone, then you can PR to modify that...?

**Comment by dthvt** [comment]
Don't know that I really have time to tackle the v210 style changes tbh.  I can re-PR after that drop if you prefer.

**Comment by shinmog** [comment]
Ok, let's do that then.  Leave this PR open for now, I'll comment in it to notify you when I've updated the module and you can PR the v210 branch.

**Comment by dthvt** [comment]
Went ahead and rebased this and added what I think are correct v210 changes.  Will resubmit shortly.

**Pull request closed without merging**
