### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by itdependsnetworks**
Was not sure how to reuse the same PR with different branches. 

I accept the ISC license.

### CODE REVIEW

**Comment by ivanbojer** [comment]
We are in the process of merging some of the modules with ansible-core and RedHat asked us to accept GPL licensing for that purpose. We will keep our library ISC but the one we merge with RedHat has to be GPL. It is in the way dual-licensed based on the usage. Would you be ok with that?

**Comment by itdependsnetworks** [comment]
Sure, just let me know the process

**Comment by itdependsnetworks** [comment]
Any updates on this?

**Comment by itdependsnetworks** [comment]
??
@ivanbojer @jtschichold

**Comment by ivanbojer** [comment]
We were in the middle of moving modules to the ansible. Unfortunately they've just changed the procedure and repo so we have to restart the effort. Just some of the modules made it and we are in the process of submitting all rest of them. Ref: https://github.com/ansible/ansible/pulls?q=is%3Apr+author%3Aivanbojer+is%3Aclosed

**Comment by ivanbojer** [comment]
Please re-submit pull request as we had to refactor the entire library due to Ansible module code practices.

**Pull request closed without merging**
